# Generated by Django 3.2.7 on 2021-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_salary', models.FloatField()),
                ('t_date_of_joining', models.DateField()),
                ('department', models.ManyToManyField(to='departmentApp.Department')),
            ],
        ),
    ]
