# Generated by Django 3.2.7 on 2021-09-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentApp', '0002_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
